### ISSUE TITLE
Anyone know how to access the IBM built system specific packages?

### ISSUE THREAD

**Issue by kaburkett** [ibm-messaging/ms03.saveqmgr#1]
In this article it mentions the utility and packages available- noting ` Even though they are labeled as withdrawn, the web pages are active and you CAN STILL DOWNLOAD the code! `

https://www.ibm.com/support/pages/steps-export-object-definitions-and-messages-one-mq-queue-manager-host-1-and-import-them-another-queue-manager-host-2-dmpmqcfg-saveqmgr

It takes you to the following link where the various packages are available:

https://www.ibm.com/support/pages/withdrawn-ms03-websphere-mq-save-queue-manager-object-definitions-using-pcfs-saveqmgr

But after accepting a disclaimer, you're forwarded to an FTP link which has enforced SSL/TLS requirements and is forcing a username and password. I was able to find this article mentioning a similar encounter:

https://www.ibm.com/support/pages/manual-file-download-when-ftp-protocol-disabled-internet-browsers

The username anonymous with the password ftp did not work for me.

**Comment by kaburkett** [comment]
Not sure @arthurbarr  if you are aware of an official IBM built package for win os or not, and how I would get my hands on it.

**Comment by arthurbarr** [comment]
It looks like you can still get hold of it via HTTP (not HTTPS) here: http://public.dhe.ibm.com/software/integration/support/supportpacs/individual/ms03_win.zip

Note that as per the page above, from MQ V7.1 onwards, the command dmpmqcfg is available in the product. This is recommended instead of the use of MS03.  This SupportPac is now withdrawn.  It hasn't been updated in 12 years, so use this at your own risk!
